// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpuxuossynzfqmuorvkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwdXh1b3NzeW56ZnFtdW9ydmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzg3MzksImV4cCI6MjA2NTU1NDczOX0.kg-LRskBDuDjh-oXgNPzZNPPJQuWj0c9HdgNVdB-6oE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);